### ISSUE TITLE
input file

### ISSUE THREAD

**Issue by ulfsv** [vxld014/TimeSeriesForecastingNeuralNets#1]
Hi Jose,
I am trying to execute this code with my own x data frame but I don't get any result (no error, no result). How should the time series data frame look like?

Best regards Ulf,

**Comment by vxld014** [comment]
Hi Ulf, 
thank you for contacting me.

A vector holding the time-series should work fine.
Suppose y is the vector holding your time series.

> cv_results = ts.cv(y, 5) # 5-fold CV MSE results
> forecasts = ts.MLP(x = y, structure = cv_results, steps = 5, epochs = 10) # Returns the k-step ahead forecast

I just ran the code and it worked for me. 
Let me know if you have additional questions.

**Comment by ulfsv** [comment]
Hi Jose,

Thanks for the help. It worked now.

Regards Ulf,

2016-03-20 6:15 GMT+01:00 Jose M. Valdovinos Alvarez <
notifications@github.com>:
